import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { format } from "date-fns";
import type { PayrollEntry, PayrollRun } from "@/lib/types";

export const generatePayslipPDF = (entry: PayrollEntry, run: PayrollRun | undefined) => {
  const doc = new jsPDF();
  const monthName = run ? format(new Date(run.year, run.month - 1), "MMMM yyyy") : "---";

  // Header
  doc.setFontSize(22);
  doc.setTextColor(40);
  doc.text("ZIPAWORLD - PAYSLIP", 105, 20, { align: "center" });
  
  doc.setFontSize(10);
  doc.text(`Employee: ${entry.employee_name || 'N/A'}`, 20, 40);
  doc.text(`Period: ${monthName}`, 20, 45);
  doc.text(`Status: ${run?.status || 'PROCESSED'}`, 20, 50);

  // Table Data
  const tableData = [
    ["Component", "Amount (INR)"],
    ["Basic Salary", `INR ${entry.basic.toLocaleString()}`],
    ["HRA", `INR ${entry.hra.toLocaleString()}`],
    ["Allowances", `INR ${entry.allowances.toLocaleString()}`],
    ["Gross Salary", `INR ${entry.gross_salary.toLocaleString()}`],
    ["", ""],
    ["Deductions", ""],
    [`LOP Deduction (${entry.lop_days} days)`, `- INR ${entry.lop_deduction.toLocaleString()}`],
    ["Attendance Penalty", `- INR ${entry.attendance_deduction.toLocaleString()}`],
    ["Fixed Deductions (Tax)", `- INR ${entry.fixed_deductions.toLocaleString()}`],
    ["Total Deductions", `- INR ${entry.total_deductions.toLocaleString()}`],
    ["", ""],
    ["NET TAKE HOME", `INR ${entry.net_salary.toLocaleString()}`],
  ];

  autoTable(doc, {
    startY: 60,
    head: [["Description", "Amount"]],
    body: tableData,
    theme: "striped",
    headStyles: { fillColor: "#4F46E5" },
    styles: { fontSize: 10 }
  });

  // Traceability Footer
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`LOP Breakdown: Absences: ${entry.absences_count}, Approved: ${entry.approved_leave_count}, Half-Days: ${entry.half_day_count}, Overlap: ${entry.overlap_count}`, 20, finalY + 10);
  doc.text("Generated by Zipaworld HR OS - Hardened Payroll Engine", 20, finalY + 15);

  doc.save(`payslip_${entry.employee_name || 'employee'}_${run?.month}_${run?.year}.pdf`);
};

export const exportPayrollExcel = (entries: PayrollEntry[], run: PayrollRun) => {
  const data = entries.map(e => ({
    "Employee Name": e.employee_name || "N/A",
    "Employee ID": e.employee_id,
    "Basic": e.basic,
    "HRA": e.hra,
    "Gross Salary": e.gross_salary,
    "LOP Days": e.lop_days,
    "LOP Deduction": e.lop_deduction,
    "Fixed Deductions": e.fixed_deductions,
    "Other Deductions": e.attendance_deduction,
    "Override Amount": e.override_amount,
    "Override Reason": e.override_reason || "",
    "Net Salary": e.net_salary
  }));

  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Payroll");
  XLSX.writeFile(workbook, `payroll_${run.month}_${run.year}.xlsx`);
};

export const exportEmployeeProfilePDF = (profile: any) => {
  if (!profile) return;

  const doc = new jsPDF();
  const basic = profile.basic || {};
  const job = profile.job || {};
  const personal = profile.personal || {};
  const summary = profile.summary || {};
  const reporting = profile.reporting || {};
  const workExperience = profile.work_experience || [];
  const education = profile.education || [];
  const dependents = profile.dependents || [];

  const empName = basic.name || `${basic.first_name || ''} ${basic.last_name || ''}`.trim() || 'Employee';
  const empCode = basic.employee_code || 'N/A';

  // Branding Header Box
  doc.setFillColor(79, 70, 229); // #4F46E5 Indigo
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("ZIPAWORLD HR OS", 14, 14);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("EMPLOYEE PROFILE DATA SHEET", 14, 22);

  const genDate = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
  doc.setFontSize(8);
  doc.text(`Generated: ${genDate}`, 196, 18, { align: "right" });

  let currentY = 36;

  const addSectionHeader = (title: string) => {
    // Check page space
    if (currentY > 260) {
      doc.addPage();
      currentY = 20;
    }
    doc.setFillColor(243, 244, 246);
    doc.rect(14, currentY, 182, 8, "F");
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(title.toUpperCase(), 18, currentY + 5.5);
    currentY += 12;
  };

  // 1. Basic & Employment Info
  addSectionHeader("1. Basic & Employment Information");
  
  const basicInfoData = [
    ["Employee Code", empCode, "Full Name", empName],
    ["Designation", basic.designation || 'Staff', "Department", job.department || 'Unassigned'],
    ["Employment Status", basic.status || 'Active', "Employee Type", job.employee_type || 'Permanent'],
    ["Work Email", basic.email || '-', "Work Phone / Ext", `${job.work_phone || '-'} / ${job.extension || '-'}`],
    ["Date of Joining", job.date_of_joining ? new Date(job.date_of_joining).toLocaleDateString('en-IN') : '-', "Work Location", job.seating_location || 'Noida'],
    ["Reporting Manager", reporting.manager?.name || job.manager || 'None', "Role / Source", `${job.work_role || 'Team Member'} (${job.source_of_hire || 'Direct'})`],
  ];

  autoTable(doc, {
    startY: currentY,
    head: [["Field", "Value", "Field", "Value"]],
    body: basicInfoData,
    theme: "grid",
    headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: "#374151" },
    columnStyles: {
      0: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 35 },
      1: { cellWidth: 56 },
      2: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 35 },
      3: { cellWidth: 56 },
    },
    margin: { left: 14, right: 14 }
  });

  currentY = (doc as any).lastAutoTable.finalY + 8;

  // 2. Personal & Contact Info
  addSectionHeader("2. Personal & Contact Details");

  const personalData = [
    ["Mobile Phone", basic.phone || '-', "Other Email", personal.other_email || '-'],
    ["Date of Birth", personal.birth_date || '-', "Gender", summary.gender || '-'],
    ["Marital Status", personal.marital_status || '-', "Father's Name", summary.fathers_name || '-'],
    ["Address", basic.address || '-', "Emergency Contact", basic.emergency_contact || '-'],
  ];

  autoTable(doc, {
    startY: currentY,
    head: [["Field", "Value", "Field", "Value"]],
    body: personalData,
    theme: "grid",
    headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: "#374151" },
    columnStyles: {
      0: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 35 },
      1: { cellWidth: 56 },
      2: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 35 },
      3: { cellWidth: 56 },
    },
    margin: { left: 14, right: 14 }
  });

  currentY = (doc as any).lastAutoTable.finalY + 8;

  // 3. Identity & Financial / Bank Details
  addSectionHeader("3. Identity & Bank Information");

  const financialData = [
    ["PAN Card No.", basic.pan || '-', "Aadhaar Card No.", basic.aadhaar || '-'],
    ["UAN Number", basic.uan || '-', "Payment Mode", personal.payment_mode || 'Bank Transfer'],
    ["Bank Name", personal.bank_name || '-', "Account Number", basic.bank_account || '-'],
    ["Account Type", personal.account_type || 'Savings', "IFSC Code", personal.ifsc_code || '-'],
    ["Bank Holder Name", personal.bank_holder_name || empName, "-", "-"],
  ];

  autoTable(doc, {
    startY: currentY,
    head: [["Field", "Value", "Field", "Value"]],
    body: financialData,
    theme: "grid",
    headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: "#374151" },
    columnStyles: {
      0: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 35 },
      1: { cellWidth: 56 },
      2: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 35 },
      3: { cellWidth: 56 },
    },
    margin: { left: 14, right: 14 }
  });

  currentY = (doc as any).lastAutoTable.finalY + 8;

  // 4. Bio & Summary
  if (summary.about_me || summary.job_description || summary.expertise) {
    addSectionHeader("4. Professional Summary & Bio");

    const summaryData = [
      ["About Me", summary.about_me || '-'],
      ["Job Description", summary.job_description || '-'],
      ["Expertise", summary.expertise || '-'],
    ];

    autoTable(doc, {
      startY: currentY,
      head: [["Topic", "Details"]],
      body: summaryData,
      theme: "grid",
      headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fontSize: 8.5, textColor: "#374151" },
      columnStyles: {
        0: { fontStyle: "bold", fillColor: "#F9FAFB", cellWidth: 40 },
        1: { cellWidth: 142 },
      },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 8;
  }

  // 5. Work Experience
  if (workExperience.length > 0) {
    addSectionHeader("5. Previous Work Experience");

    const expData = workExperience.map((exp: any) => [
      exp.company_name || '-',
      exp.job_title || '-',
      `${exp.from_date || '-'} to ${exp.to_date || '-'}`,
      exp.description || '-'
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [["Company", "Job Title", "Period", "Description"]],
      body: expData,
      theme: "striped",
      headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fontSize: 8.5, textColor: "#374151" },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 8;
  }

  // 6. Education
  if (education.length > 0) {
    addSectionHeader("6. Education Records");

    const eduData = education.map((edu: any) => [
      edu.institute || '-',
      edu.degree || '-',
      edu.specialization || '-',
      edu.passing_year || '-',
      edu.gpa || '-'
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [["Institute", "Degree", "Specialization", "Passing Year", "GPA / Marks"]],
      body: eduData,
      theme: "striped",
      headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fontSize: 8.5, textColor: "#374151" },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 8;
  }

  // 7. Dependents
  if (dependents.length > 0) {
    addSectionHeader("7. Dependents");

    const depData = dependents.map((dep: any) => [
      dep.name || '-',
      dep.relationship || '-',
      dep.age || '-',
      dep.dob || '-'
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [["Name", "Relationship", "Age", "Date of Birth"]],
      body: depData,
      theme: "striped",
      headStyles: { fillColor: "#312E81", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fontSize: 8.5, textColor: "#374151" },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 8;
  }

  // Footer for each page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`Zipaworld HR OS • Confidential Employee Profile • Page ${i} of ${pageCount}`, 105, 290, { align: "center" });
  }

  const sanitizedFileName = (empName || "Employee").replace(/[^a-zA-Z0-9_-]/g, "_");
  doc.save(`Employee_Profile_${sanitizedFileName}_${empCode}.pdf`);
};

