from enum import Enum

class ApplicationStatus(str, Enum):
    APPLIED = "APPLIED"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW_L1 = "INTERVIEW_L1"
    INTERVIEW_L2 = "INTERVIEW_L2"
    INTERVIEW_L3 = "INTERVIEW_L3"
    INTERVIEW_L4 = "INTERVIEW_L4"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"
    OFFER_CREATED = "OFFER_CREATED"
    OFFER_SENT = "OFFER_SENT"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    ONBOARDING_STARTED = "ONBOARDING_STARTED"
    JOINED = "JOINED"

class OfferStatus(str, Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    DECLINED = "DECLINED"
    CANCELLED = "CANCELLED"

class EmployeeStatus(str, Enum):
    ONBOARDING = "ONBOARDING"
    ACTIVE = "ACTIVE"
    EXIT_PROCESS = "EXIT_PROCESS"
    EXITED = "EXITED"

class LeaveStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class AssetStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    UNDER_REPAIR = "UNDER_REPAIR"
    RETIRED = "RETIRED"

class TicketStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class SLAStatus(str, Enum):
    ON_TRACK = "ON_TRACK"
    AT_RISK = "AT_RISK"
    BREACHED = "BREACHED"

class OnboardingStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"

class DayType(str, Enum):
    FULL_DAY = "FULL_DAY"
    FIRST_HALF = "FIRST_HALF"
    SECOND_HALF = "SECOND_HALF"

class AccrualType(str, Enum):
    NONE = "NONE"
    MONTHLY = "MONTHLY"
    YEARLY = "YEARLY"

class AttendanceStatus(str, Enum):
    PRESENT = "PRESENT"
    LATE = "LATE"
    HALF_DAY = "HALF_DAY"
    ABSENT = "ABSENT"

class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    MANUAL = "MANUAL"

class RegularizationStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class AuditAction(str, Enum):
    # Employee & Onboarding
    EMPLOYEE_CREATED = "EMPLOYEE_CREATED"
    EMPLOYEE_UPDATED = "EMPLOYEE_UPDATED"
    EMPLOYEE_DELETED = "EMPLOYEE_DELETED"
    ONBOARDING_STARTED = "ONBOARDING_STARTED"
    ONBOARDING_COMPLETED = "ONBOARDING_COMPLETED"
    
    # Offers
    OFFER_CREATED = "OFFER_CREATED"
    OFFER_SENT = "OFFER_SENT"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    OFFER_DECLINED = "OFFER_DECLINED"
    
    # Leave
    LEAVE_APPLIED = "LEAVE_APPLIED"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"
    
    # Ticketing
    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"
    TICKET_RESOLVED = "TICKET_RESOLVED"
    
    # Attendance
    ATTENDANCE_CHECK_IN = "ATTENDANCE_CHECK_IN"
    ATTENDANCE_CHECK_OUT = "ATTENDANCE_CHECK_OUT"
    
    # Admin & Roles
    ROLE_CREATED = "ROLE_CREATED"
    ROLE_UPDATED = "ROLE_UPDATED"
    ROLE_DELETED = "ROLE_DELETED"
    PERMISSION_CHANGED = "PERMISSION_CHANGED"
    DEPARTMENT_CREATED = "DEPARTMENT_CREATED"
    CONFIG_UPDATED = "CONFIG_UPDATED"
    
    # Payroll
    PAYROLL_RUN = "PAYROLL_RUN"
    PAYROLL_LOCKED = "PAYROLL_LOCKED"
    PAYROLL_PAID = "PAYROLL_PAID"
    
    # Performance
    PERFORMANCE_CYCLE_CREATED = "PERFORMANCE_CYCLE_CREATED"
    PERFORMANCE_CYCLE_ACTIVATED = "PERFORMANCE_CYCLE_ACTIVATED"
    KPA_CREATED = "KPA_CREATED"
    KRA_CREATED = "KRA_CREATED"
    GOALS_SUBMITTED = "GOALS_SUBMITTED"
    GOALS_APPROVED = "GOALS_APPROVED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_STEP_COMPLETED = "REVIEW_STEP_COMPLETED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    RATING_OVERRIDDEN = "RATING_OVERRIDDEN"
    
    # Auth
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    
    # Phase 3
    APPRAISAL_GENERATED = "APPRAISAL_GENERATED"
    APPRAISAL_UPDATED = "APPRAISAL_UPDATED"
    APPRAISAL_LOCKED = "APPRAISAL_LOCKED"
    PROMOTION_PROPOSED = "PROMOTION_PROPOSED"
    PROMOTION_APPROVED = "PROMOTION_APPROVED"
    PERFORMANCE_SNAPSHOT_CREATED = "PERFORMANCE_SNAPSHOT_CREATED"
    
    # AI Config
    AI_CONFIG_UPDATED = "AI_CONFIG_UPDATED"

class PayrollStatus(str, Enum):
    DRAFT = "DRAFT"
    LOCKED = "LOCKED"
    PAID = "PAID"

class PerformanceCycleStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"

class CycleType(str, Enum):
    MID_YEAR = "MID_YEAR"
    ANNUAL = "ANNUAL"

class GoalStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class ReviewStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"

class ReviewStepRole(str, Enum):
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    HR = "HR"

class ReviewActionType(str, Enum):
    SELF_REVIEW = "SELF_REVIEW"
    MANAGER_REVIEW = "MANAGER_REVIEW"
    FINAL_APPROVAL = "FINAL_APPROVAL"

class ActionStatus(str, Enum):
    PENDING = "PENDING"
    DONE = "DONE"
    SKIPPED = "SKIPPED"

class AppraisalStatus(str, Enum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"

class PromotionStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class SalaryChangeReason(str, Enum):
    APPRAISAL = "APPRAISAL"
    PROMOTION = "PROMOTION"
    MANUAL = "MANUAL"

class AISource(str, Enum):
    AI = "AI"
    RULE = "RULE"

class AIUsageStatus(str, Enum):
    PENDING = "PENDING"
    USED = "USED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
